### ISSUE TITLE
Create and Add a '.gitignore' file

### ISSUE THREAD

**Issue by e-lemma** [Zhi-704/C11-Kappa-Group-Project#10]
### Tasks:

- [x] Create a '.gitignore' file
- [ ] Add it to repository 

### User story

As a developer, I need to git to ignore specific files, so unecessary or sensitive files aren't pushed.

**Comment by Faris-Abulula** [comment]
Include:
.env
.venv
.terraform
.terraform.lock.hcl
*.tfstate
*.tfstate.backup
*.tfvars
